### ISSUE TITLE
Force Fix 

### ISSUE THREAD

**Issue by ghaem51** [ehsan-mohammadi/Doodle-Jump-Unity3D-Game#1]
https://github.com/ehsan-mohammadi/Doodle-Jump-Unity3D-Game/blob/6a550147c980bc5ded4dde9f619ee0ba19d3e75f/Assets/Scripts/Platform.cs#L65
fix:
if (-Other.relativeVelocity.y >= 0f)

**Comment by ehsan-mohammadi** [comment]
Thanks.
But for me "if (-Other.relativeVelocity.y <= 0f)" works fine. For me, the relative velocity is platform.velocity.y - doodler.velocity.y. "if (-Other.relativeVelocity.y >= 0f)" is correct when relative velocity = doodler.velocity.y - platform.velocity.y.

This may have occurred because Unity rigidbody has some bugs.
